### ISSUE TITLE
Operation error

### ISSUE THREAD

**Issue by vickyyd** [zabaras/deep-turbulence#1]
Hello, This is an outstanding job. But there is some error when i train model in colab. I followed the tutorial, but threw the following error. How can i solve this problem. Thank you.
```
[15:07:00][Output]: Testing Model
Traceback (most recent call last):
  File "main.py", line 109, in <module>
    loss = modelTrainer.test(model, samples=2, epoch=epoch)
  File "/content/deep-turbulence/tmglow/nn/trainFlowParallel.py", line 359, in test
    yPred0, logp, a0 = model.gather(outputs, self.args.src_device)
  File "/usr/local/lib/python3.7/dist-packages/torch/nn/parallel/data_parallel.py", line 180, in gather
    return gather(outputs, output_device, dim=self.dim)
  File "/usr/local/lib/python3.7/dist-packages/torch/nn/parallel/scatter_gather.py", line 76, in gather
    res = gather_map(outputs)
  File "/usr/local/lib/python3.7/dist-packages/torch/nn/parallel/scatter_gather.py", line 63, in gather_map
    return Gather.apply(target_device, dim, *outputs)
  File "/usr/local/lib/python3.7/dist-packages/torch/nn/parallel/_functions.py", line 56, in forward
    assert all(i.device.type != 'cpu' for i in inputs), (
  File "/usr/local/lib/python3.7/dist-packages/torch/nn/parallel/_functions.py", line 56, in <genexpr>
    assert all(i.device.type != 'cpu' for i in inputs), (
AttributeError: 'list' object has no attribute 'device
```

**Comment by NickGeneva** [comment]
Hi,

I have not seen this error before, but seems its complaining about the [`nn.parallel.gather`](https://pytorch.org/tutorials/beginner/former_torchies/parallelism_tutorial.html), likely because the recurrent states of the model are tensors in a list. What version of PyTorch are you using?

Regardless, this really just takes the outputs of the model and moves everything onto a single device. You could override the gather function in the [parallel file](https://github.com/zabaras/deep-turbulence/blob/0daca5daada449d4ba16bce37b703e20b444b6bc/tmglow/utils/parallel.py#L163) which will just return the same outputs and then I believe move the predictions onto the same device. For example, for the prediction state I think this would look something like:

```python

# Sample model
outputs = model.sample(input[:,tstep], a0)                    
yPred0, logp, a0 = model.gather(outputs, self.args.src_device)

# Loop through output list of outputs on each device and get the prediction (first item in each tuple)
yPred0 = []
for output in outputs:
   yPred0.append(output[0].to(args.src_device))

# Concate outputs on different devices on the batch dimension
yPred0 = torch.cat(yPred0, dim=0)

```

I believe you would have to repeat this process for both the `logp` and `a0` (output[1] and output[2]), but `a0` is a list of tuples that will need to be iterated through and concatenated individually.

**Comment by vickyyd** [comment]
Hi, thank you. 

You can see the problem in the link 
`https://colab.research.google.com/drive/1iaNyyXDECJOJ9F3NpVonx7ssPCEdiix_?usp=sharing`
The version of PyTorch is 1.8.1+cu101.
How should I modify the project? Should I insert these code at the \until\parallel.py or main.py?
```
# Sample model
outputs = model.sample(input[:,tstep], a0)                    
yPred0, logp, a0 = model.gather(outputs, self.args.src_device)

# Loop through output list of outputs on each device and get the prediction (first item in each tuple)
yPred0 = []
for output in outputs:
   yPred0.append(output[0].to(args.src_device))

# Concate outputs on different devices on the batch dimension
yPred0 = torch.cat(yPred0, dim=0)
``` 
Thank you.

**Comment by NickGeneva** [comment]
Sorry about the delay. Thanks for linking the collab notebook. I've copied it to get it running and made the quick and dirty edit to get it running on a single GPU.

In `utils/parallel.py` uncomment the [gather function](https://github.com/zabaras/deep-turbulence/blob/master/tmglow/utils/parallel.py#L163) and update it to the code below. Since things are running on a single GPU seems the gather request is getting confused. This is my fault since I ran everything on multi-gpu's I have not thoroughly tested on a single GPU set up.

```python
def gather(self, outputs, output_device):
        if not self.device_ids or len(self.device_ids) == 1:
          return outputs
        return gather(outputs, output_device)
```

With this the collab notebook seems to be training and testing. Let me know if this doesn't fix it.

Thanks.

**Comment by vickyyd** [comment]
Hi, thank you for your selfless sharing. This problem has been fixed by your code. 
Actually, I meet another problem. 
```
Traceback (most recent call last):
  File "main.py", line 98, in <module>
    loss = modelTrainer.trainParallel(model, optimizer, epoch=epoch)
  File "/content/deep-turbulence/tmglow/nn/trainFlowParallel.py", line 287, in trainParallel
    loss.backward()
  File "/usr/local/lib/python3.7/dist-packages/torch/tensor.py", line 245, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph, inputs=inputs)
  File "/usr/local/lib/python3.7/dist-packages/torch/autograd/__init__.py", line 147, in backward
    allow_unreachable=True, accumulate_grad=True)  # allow_unreachable flag
RuntimeError: Trying to backward through the graph a second time, but the saved intermediate results have already been freed. Specify retain_graph=True when calling .backward() or autograd.grad() the first time.
```
The new problem doesn't come up very often. I trained four times, and I showed up twice.
I fixed it by change nn/trainFlowParallel.py in line 287 to `loss.backward(retain_graph=True)`. At the same time, the occupation of GPU memory is significantly improved. I'm evaluating the impact of this change on the final result.
And the link is 
`https://colab.research.google.com/drive/1eTb10rLBPrfjtwF8QBjVdqC7BSDWkVSL?usp=sharing`
Thank you.

**Comment by NickGeneva** [comment]
Hmm, I am unsure about this error. Particularly since it will only show up occasionally for you, I have not experienced this error (both on my GPUs and also the collab notebook) as a right now. Is there any particular pattern this seems to be occurring with? E.g. after a test prediction, certain epoch, on loading a pretrained model, etc.

Regarding `retain_graph=True`, this should not be necessary and actually should not be used since PyTorch should create its backprop graph every training iteration based on my understanding.

**Comment by vickyyd** [comment]
Hi, `retain_graph=True` is unnecessary, it will cause the model to diverge.

And this `RuntimeError: Trying to backward through the graph a second time, but the saved intermediate results have already been freed. Specify retain_graph=True when calling .backward() or autograd.grad() the first time.` error usually happens after the loss growing very fast. Such as  
```
[05:27:29][Output]: Train Epoch: 65; Mini-batch: 4/12 (33%); 	 Current Loss: 2804.953613
[05:28:23][Output]: Train Epoch: 65; Mini-batch: 9/12 (75%); 	 Current Loss: 249221040604358639616.000000
[05:28:45][Output]: Epoch 65: Sample Training Loss: 7.445546324163935e+24
[05:28:45][Output]: Learning-rate: 0.00072
[05:28:45][Output]: Testing Model
[05:28:49][Output]: Plotting predictions.
[05:29:02][Output]: Epoch 65: Testing Loss: 1.2536101703258294e+22
[05:29:02][Output]: Epoch 65, Saving network!
[SaveWorkspace] Saving PyTorch model to file.
[SaveWorkspace] Saving arguements to file.
[SaveWorkspace] Compressing workspace to zip file.
[SaveWorkspace] Saved workspace.
[05:29:03][Output]: tsteps: 43
Beta: 200
[05:29:57][Output]: Train Epoch: 66; Mini-batch: 4/12 (33%); 	 Current Loss: 1249812806493077511348420608.000000
[05:30:52][Output]: Train Epoch: 66; Mini-batch: 9/12 (75%); 	 Current Loss: 4504794662791823125882339328.000000
[05:31:13][Output]: Epoch 66: Sample Training Loss: 5.943414617245801e+27
[05:31:13][Output]: Learning-rate: 0.00072
[05:31:13][Output]: tsteps: 43
Beta: 200
[05:32:08][Output]: Train Epoch: 67; Mini-batch: 4/12 (33%); 	 Current Loss: 5587276168348565756463546368.000000
Traceback (most recent call last):
``` 
And
```
[09:58:35][Output]: Train Epoch: 100; Mini-batch: 4/24 (17%); 	 Current Loss: 2188.228027
[09:59:20][Output]: Train Epoch: 100; Mini-batch: 9/24 (38%); 	 Current Loss: 4481.615723
[10:00:05][Output]: Train Epoch: 100; Mini-batch: 14/24 (58%); 	 Current Loss: 9327811.000000
[10:00:51][Output]: Train Epoch: 100; Mini-batch: 19/24 (79%); 	 Current Loss: 2251755008586416128.000000
[10:01:27][Output]: Epoch 100: Sample Training Loss: 1.140220122204639e+20
[10:01:27][Output]: Learning-rate: 0.00061
[10:01:27][Output]: Testing Model
[10:01:31][Output]: Plotting predictions.
[10:01:46][Output]: Epoch 100: Testing Loss: 1.3135130977632256e+16
[10:01:46][Output]: Epoch 100, Saving network!
[SaveWorkspace] Saving PyTorch model to file.
[SaveWorkspace] Saving arguements to file.
[SaveWorkspace] Compressing workspace to zip file.
[SaveWorkspace] Saved workspace.
[10:01:48][Output]: tsteps: 60
Beta: 200
[10:02:33][Output]: Train Epoch: 101; Mini-batch: 4/24 (17%); 	 Current Loss: 1195398189654810296320.000000
[10:03:19][Output]: Train Epoch: 101; Mini-batch: 9/24 (38%); 	 Current Loss: 2368408141137031725056.000000
Traceback (most recent call last):
```
Can you help me? 
Thank you.

**Comment by NickGeneva** [comment]
I see, yeah, if the model diverges then things can likely go wrong on multiple fronts.

My suggestion if you're seeing your model diverge (which could be due to the reduced mini-batch size or basically any factor) would be to lower to gradient clipping value. This can be adjusted through using the [`max_grad_norm` argument](https://deep-turbulence.readthedocs.io/en/latest/tmglow/args.html). So perhaps try 

`python main.py --batch-size 8 --max-grad-norm 0.005` 

or something like that. The default values for each case can be referenced in the code or on the [docs](https://deep-turbulence.readthedocs.io/en/latest/tmglow/args.html). The only catch is that this may slow training convergence...

You don't need to restart from scratch either, just simply pick up training from a recent checkpoint with stable learning with the `--epoch-start #` parameter. There are some few additional ideas for stabilizing the model on the [docs faq page](https://deep-turbulence.readthedocs.io/en/latest/faq.html).

**Comment by vickyyd** [comment]
Hi, `max-grad-norm` seem to be useful.  The program didn't go wrong.
Thank you.

**Comment by NickGeneva** [comment]
Good, I will close this issue for now since it seems you've got things running. Feel free to re-open or create another if you have any additional questions/concerns.
